### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by Itrulia** [andreasonny83/angular6-monorepo-experiment#1]
Hey! This is all I needed to get started. I just wanted to look into lerna + angular/cli v6 and this even included `git cz`. Thank you very much, you just saved me a lot.

**Comment by andreasonny83** [comment]
Thanks for your feedback. Please, let me know if you make any progress from here so I can also learn something new 😄

**Comment by Itrulia** [comment]
Currently trying to figure out how to modify some @angular/cli behaviour. Trying to add scss-bundler support.

Most of it is pretty well explained in the readme already and it seems like lerna <3 angular/cli
